// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Category struct {
	ID   int32
	Name string
}

type Task struct {
	ID          int32
	Title       string
	Description sql.NullString
	Status      sql.NullString
	Priority    sql.NullString
	DueDate     sql.NullTime
	UserID      sql.NullInt32
}

type TaskCategory struct {
	TaskID     int32
	CategoryID int32
}

type User struct {
	ID           int32
	Username     string
	PasswordHash string
	Role         sql.NullString
}
